### ISSUE TITLE
Unable to run extension

### ISSUE THREAD

**Issue by spetersisc** [vince-fugnitto/theia-custom-getting-started#1]
After cloning the repo and using yarn to build it, there are errors due to engine parameters in package.json. When those are removed there are other issues? Is there updates needed so it runs properly with theia v1.9?

**Comment by vince-fugnitto** [comment]
@spetersisc it has been updated to use `1.9.0` https://github.com/vince-fugnitto/theia-custom-getting-started/commit/659bb5f738b8ee63e9aee5999ffdf206f6e2eab3, the only issue was removing the deprecated extensions.
